#!/bin/sh

case "$1" in
start)
    echo "Loading LDD modules"
    
    # create device nodes

    # scull
    rm -f /dev/scull*
    mknod /dev/scull c 248 0
    mknod /dev/scullp c 248 1
    mknod /dev/sculla c 248 2

    # faulty
    rm -f /dev/faulty
    mknod /dev/faulty c 247 0

    # load modules
    modprobe scull
    modprobe faulty
    modprobe hello

    ;;
stop)
    echo "Unloading LDD modules"

    # unload modules
    rmmod hello || true
    rmmod faulty || true
    rmmod scull || true

    ;;
restart)
    $0 stop
    $0 start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
