#!/bin/sh
case "$1" in
    start)
        echo "Loading aesdchar driver..."
        # Rufe das Lade-Skript auf (wird nach /usr/bin kopiert)
        aesdchar_load
        ;;
    stop)
        echo "Unloading aesdchar driver..."
        # Rufe das Entlade-Skript auf
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
