name: assignment-test
on:
  push:
    branches:
      - '*'

jobs:
  full-test-assignment5buildroot:
    container: cuaesd/aesd-autotest:24-assignment5-buildroot
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Cleanup previous runs
        run: killall -9 qemu-system-aarch64 || true
      - name: Install sshpass
        run: |
          apt-get update
          apt-get install -y sshpass
      - name: Run unit test
        run: ./unit-test.sh
      - name: Fix workspace permissions
        if: always()
        run: chown -R 1000:1000 .

  full-test-assignment5final:
    needs: full-test-assignment5buildroot
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Cleanup previous runs
        run: sudo killall -9 qemu-system-aarch64 || true
      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER .
      - name: Install dependencies on host
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
      - name: Run full test
        run: ./full-test.sh
